name: Test

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          version: 11
          runtime: node@24
          cache: true
      - name: Install gettext
        run: sudo apt update && sudo apt install gettext
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm run test:coverage
